<body>
<script>
function log(msg) {
  let e = document.createElement('div');
  e.innerText = msg;
  document.body.appendChild(e);
}
const a = /x/;
function assertThrows(f, expected_exception) {
  try {
    f();
  } catch (e) {
    log('thrown ' + e + '; expecting throw ' + expected_exception);
    return;
  }
  log('not expected');
}

a.exec = RegExp.prototype.test;
assertThrows(() => RegExp.prototype.test.call(a), RangeError);
</script>
</body>
