<body>
<script>
function log(msg) {
  let e = document.createElement('div');
  e.innerText = msg;
  document.body.appendChild(e);
}
function assertThrows(f, expected_exception) {
  try {
    f();
  } catch (e) {
    log('thrown ' + e + '; expecting throw ' + expected_exception);
    return;
  }
  log('not expected');
}
assertThrows(function() {
  var memory = new WebAssembly.Memory({initial: 64 * 1024 * 1024 / 0x10000});
  var array = new Uint8Array(memory.buffer);
  Uint8Array.of.call(function() { return array },
                    {valueOf() { memory.grow(1); } });
}, TypeError);

assertThrows(function() {
  var memory = new WebAssembly.Memory({initial: 64 * 1024 * 1024 / 0x10000});
  var array = new Uint8Array(memory.buffer);
  Uint8Array.from.call(function() { return array },
                       [{valueOf() { memory.grow(1); } }],
                       x => x);
}, TypeError);
</script>
<body>
